[package]
name = "syn-internal-codegen"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>", "Nika Layzell <nika@thelayzells.com>"]
edition = "2018"

publish = false # this is an internal crate which should never be published

[dependencies]
anyhow = "1.0"
color-backtrace = "0.2"
indexmap = { version = "1.0", features = ["serde-1"] }
inflections = "1.1"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
quote = "1.0"
rustfmt = { package = "rustfmt-nightly", git = "https://github.com/rust-lang-nursery/rustfmt" }
semver = { version = "0.9", features = ["serde"] }
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0.38"
syn-codegen = { path = "../json" }
syn = { path = "..", features = ["full", "extra-traits"] }
thiserror = "1.0"
toml = "0.4.10"

# work around https://github.com/crossbeam-rs/crossbeam/issues/435
# until https://github.com/BurntSushi/ripgrep/pull/1427 is released
crossbeam-utils = "=0.6.5"

[workspace]
# Prefer that `cargo clean` in syn's directory does not require a rebuild of
# rustfmt in the codegen directory.
