# This is an example configuration file for nitrocli. To use it, place it at
# ${XDG_CONFIG_HOME}/nitrocli/config.toml, where XDG_CONFIG_HOME defaults to
# ${HOME}.

# The model to connect to (string, "pro" or "storage", default: not set).
model = "pro"
# The serial number of the device to connect to (list of strings, default:
# empty).
serial_numbers = ["0xf00baa", "deadbeef"]
# The USB path of the device to connect to (string, default: empty).
usb_path = "004:001:00"
# Do not cache secrets (boolean, default: false).
no_cache = true
# The log level (integer, default: 0).
verbosity = 2
