language: rust

rust:
  - nightly
  - beta
  - stable
  - 1.31.0

script:
  - cargo test

matrix:
  include:
    - rust: nightly
      name: Minimal versions
      before_script:
        - cargo update -Z minimal-versions
