# Cargo.toml

# Copyright (C) 2021 The Nitrocli Developers
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "nitrocli-ext"
version = "0.1.0"
authors = ["Robin Krahl <robin.krahl@ireas.org>"]
edition = "2018"

[dependencies]
anyhow = "1"
directories = "3"
nitrokey = "0.9"
